# Streamlit Secrets Configuration
# This file should be created in Streamlit Cloud's secrets management
# Copy this template and replace with your actual credentials

[credentials]
# Add your actual usernames and passwords here
# Example:
# admin = "your_secure_password_here"
# user1 = "another_secure_password"
# demo = "demo_password"

# For production, use strong passwords!
# You can generate them using: python -c "import secrets; print(secrets.token_urlsafe(32))"